name: devmov_tarefa_floor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  floor: any
  sqflite: any
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  dio: any
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  floor_generator: ^1.4.2

flutter:
  generate: true
  uses-material-design: true
